# Generated by Django 4.0.5 on 2022-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manage_app', '0002_alter_users_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
