# Generated by Django 4.0.5 on 2022-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manage_app', '0003_books_alter_users_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
