# Generated by Django 4.0.5 on 2022-06-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manage_app', '0005_users_id_alter_users_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table=None,
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
