# Generated by Django 4.0.5 on 2022-06-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manage_app', '0007_usersss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersss',
        ),
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
