# Generated by Django 4.0.5 on 2022-06-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manage_app', '0009_rename_publication_books_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='publications',
            new_name='publication',
        ),
    ]
