# Generated by Django 4.0.5 on 2022-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manage_app', '0011_remove_books_id_alter_books_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='total_pages',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='author_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='publication',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
