# Generated by Django 4.0.5 on 2022-06-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manage_app', '0013_alter_users_email_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
