# Generated by Django 4.0.5 on 2022-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_manage_app', '0014_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
